In [71]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [72]:
df=pd.read_csv("attrition.csv")

In [73]:
df.shape

(10000, 14)

In [107]:
import pandas as pd
from random import sample

# Split the samples based on class

attrition_0 = df[df.Exited==0]
attrition_1 = df[df.Exited==1]

# random sampling majority class
attrition_0=attrition_0.reset_index()
sample_index = sample(range(len(attrition_0)), len(attrition_1))
attrition_0_sample = attrition_0.iloc[sample_index]
print("No of rows after sampling", len(attrition_0_sample))


# after this we have equal number of instances for both the classes

df = pd.concat([attrition_1,attrition_0_sample])

No of rows after sampling 2037


In [75]:
# hot encode Gender parameter

for i in range(len(df)):
    if(df.Gender.values[i]=='Male'):
        df.Gender.values[i]=1
    else:
        df.Gender.values[i]=0
        
df.Gender=df.Gender.astype(float)

In [76]:
df.columns
df=df[['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited']]
df

RowNumber  CustomerId           Surname  CreditScore Geography  Gender  \
0             1    15634602          Hargrave          619    France     0.0   
2             3    15619304              Onio          502    France     0.0   
5             6    15574012               Chu          645     Spain     1.0   
7             8    15656148            Obinna          376   Germany     0.0   
16           17    15737452             Romeo          653   Germany     1.0   
...         ...         ...               ...          ...       ...     ...   
3187       4045    15607142            Parkin          658    France     1.0   
5750       7241    15591552           Okonkwo          600    France     0.0   
7219       9099    15713559  Onyemauchechukwu          473   Germany     0.0   
2267       2875    15733581            Duncan          831   Germany     1.0   
1341       1699    15807595            Ijendu          485   Germany     1.0   

      Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      42       2       0.00              1          1               1   
2      42       8  159660.80              3          1               0   
5      44       8  113755.78              2          1               0   
7      29       4  115046.74              4          1               0   
16     58       1  132602.88              1          1               0   
...   ...     ...        ...            ...        ...             ...   
3187   32       8       0.00              1          1               1   
5750   32       7   98877.95              1          1               0   
7219   32       5  146602.25              2          1               1   
2267   32       9   80262.66              1          1               0   
1341   51       7  144244.59              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
2           113931.57       1  
5           149756.71       1  
7           119346.88       1  
16            5097.67       1  
...               ...     ...  
3187         80410.68       0  
5750        132973.21       0  
7219         72946.95       0  
2267        194867.78       0  
1341         51113.14       0  

[4074 rows x 14 columns]

In [81]:
#One hot encoding the 'Geography' parameter to incorporate it into the model
df.Geography.value_counts()

for i in range(len(df)):
    if(df.Geography.values[i]=='France'):
        df.Geography.values[i]=0
    if(df.Geography.values[i]=='Germany'):
        df.Geography.values[i]=1
    if(df.Geography.values[i]=='Spain'):
        df.Geography.values[i]=2
        
df.Geography=df.Geography.astype(float)

In [83]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [84]:
#train test split

from sklearn.model_selection import train_test_split

Xtrain, Xtest, Ytrain, Ytest= train_test_split(df[['CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember']], df[['Exited']], test_size=0.2, random_state=55)

In [85]:
# model
from sklearn.tree import DecisionTreeClassifier

clf_entropy=DecisionTreeClassifier(max_depth=10,max_leaf_nodes=10,min_samples_leaf=10,criterion='entropy')

In [86]:
#model train

clf_entropy.fit(Xtrain,Ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_leaf_nodes=10,
                       min_samples_leaf=10)

In [87]:
#predict
Ypred=clf_entropy.predict(Xtest)

In [88]:
# metrics

from sklearn.metrics import confusion_matrix, accuracy_score

acc=accuracy_score(Ytest,Ypred)
cm=confusion_matrix(Ytest,Ypred)

In [89]:
acc

0.7079754601226994

In [90]:
cm

array([[320,  87],
       [151, 257]], dtype=int64)

# -----------------------------------------------------------------------------#

In [92]:
#train test split

from sklearn.model_selection import train_test_split

Xtrain, Xtest, Ytrain, Ytest= train_test_split(df[['CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember']], df[['Exited']], test_size=0.2, random_state=195)

In [93]:
# random forest

from sklearn.ensemble import RandomForestClassifier

clf_entropy=RandomForestClassifier(n_estimators=100)

In [94]:
#model train

clf_entropy.fit(Xtrain,Ytrain)

RandomForestClassifier()

In [95]:
#predict
Ypred=clf_entropy.predict(Xtest)

In [96]:
# metrics

from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

acc=accuracy_score(Ytest,Ypred)
cm=confusion_matrix(Ytest,Ypred)
f=f1_score(Ytest,Ypred)

In [97]:
print("Accuracy:",acc)

Accuracy: 0.7693251533742331


In [98]:
print("F1-score:",f)

F1-score: 0.769607843137255


In [99]:
cm

array([[313,  97],
       [ 91, 314]], dtype=int64)

# ---------------------------------------------------------------------------------#

In [51]:
# model
from sklearn.neighbors import KNeighborsClassifier 

clf_entropy=KNeighborsClassifier(n_neighbors=5,p=2,weights='uniform')

#model train

clf_entropy.fit(Xtrain,Ytrain)

#predict
Ypred=clf_entropy.predict(Xtest)

# metrics

from sklearn.metrics import confusion_matrix, accuracy_score

acc=accuracy_score(Ytest,Ypred)
cm=confusion_matrix(Ytest,Ypred)

print(cm)

acc

[[232 178]
 [155 250]]


0.5914110429447853

# as we can see that this performed poorly, let's try SVM

In [52]:
# model
from sklearn.svm import SVC

clf_entropy=SVC(kernel='linear')

#model train

clf_entropy.fit(Xtrain,Ytrain)

#predict
Ypred=clf_entropy.predict(Xtest)

# metrics

from sklearn.metrics import confusion_matrix, accuracy_score

acc=accuracy_score(Ytest,Ypred)
cm=confusion_matrix(Ytest,Ypred)

print(cm)

acc

[[205 205]
 [ 68 337]]


0.6650306748466258

# this too is performing a little poor, so let's move on to the gradient boosting algorithm

In [104]:
# model
from sklearn.ensemble import GradientBoostingClassifier

clf_entropy=GradientBoostingClassifier(n_estimators=100)

#model train

clf_entropy.fit(Xtrain,Ytrain)

#predict
Ypred=clf_entropy.predict(Xtest)

# metrics

from sklearn.metrics import confusion_matrix, accuracy_score

acc=accuracy_score(Ytest,Ypred)
cm=confusion_matrix(Ytest,Ypred)

print(cm)

print("Accuracy:",acc)

[[325  85]
 [ 82 323]]
Accuracy: 0.7950920245398773


# this is a good score comparing with the other algorithms

In [106]:
# we should check if there's overfitting problem or not

from sklearn.model_selection import cross_val_score

scores=cross_val_score(clf_entropy, Xtrain, Ytrain, cv=10)
print("Average validation score:", np.mean(scores))

Average validation score: 0.7744719207173194


# as we can see that validation score is not that far off from the test score so it's safe to say there's a little or no overfitting here.